#+TITLE: setup-elemetary-os
#+DATE: 2015-08-26
#+SETUPFILE: ~/Dev/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES:
#+JEKYLL_PUBLISHED: true

本文记录了配置我的ElementaryOS的过程。

{{{more}}}

* 用户脚本目录.usrbin
在 =~/= 目录下面，创建一个.usrbin文件夹，并且在 ~/.profile 里把它放置到PATH的最前面。
#+begin_src sh
export $PATH=$HOME/.usrbin:$PATH
#+end_src

执行命令 =source ~/.profile= 使改动立即生效。

里面可以放一些你自己写的shell脚本、python脚本等，还可以用同名的命令覆盖系统命令，比如emacs，sublime，在修改emacs启动闪退，sublime中文支持上面很方便。

例如，用scratch创建一个text文件 =scratch-text-editor ~/.usrbin/text=, 其中，内容如下
#+begin_src sh
#!/bin/bash
GTK_IM_MODULE="xim" exec /usr/bin/scratch-text-editor "$@"
#+end_src

然后，用chmod添加可执行的属性， =chmod +x ~/.usrbin/text=

现在就可以在命令行下面，使用text打开scratch了，会方便很多。同时，前缀GTK_IM_MODULE="xim"是使scratch支持中文输入法。

* 改主机名称
装系统的时候，脑子一抽把主机名子起的特别难听。在命令行下面不好看，后来专门去网搜了一下怎么改主机名，把方法在这记录一下。\\

先执行命令 =sudo text /etc/hostname= ,文件里面存储的是旧的计算机名字，把它改为你想要的名字。我给改成了eOS。保存。

运行命令 =sudo gedit /etc/hosts= ，里面的内容大概如下。更改127.0.1.1位置的值，使它跟你刚才输入的计算机名字相符，完成后保存文件。
#+begin_src sh
127.0.0.1 localhost
127.0.1.1 eOS
#+end_src

重启后，机器就会显示新的名字了。

参考：
- [[http://os.51cto.com/art/201311/416060.htm][Ubuntu每日小技巧——怎样修改你的计算机名字]]

* 安装Emacs24.5
emacs最新的24.5没有deb包，只能从源码安装了。下载最新的24.5的tar.xz包 http://ftpmirror.gnu.org/emacs/

在下载emacs源码的过程中，可以安装其他需要用到的工具。
#+begin_src sh
sudo apt-get install checkinstall
sudo apt-get install build-essential
sudo apt-get build-dep emacs24
#+end_src

下载文件为emacs-24.5.tar.xz。邮件Extract Here，进入该文件夹再邮件 Open In -> Terminal。依次执行以下命令。
#+begin_src sh
./configure --prefix=/usr
make
checkinstall
#+end_src

其中，--prefix参数是指定emacs安装的目录。我习惯安装在usr目录，而不是默认的/usr/local目录。checkinstall命令是将编译好的emacs打包成deb包，然后用户再用gdebi安装，这样的好处是，可以方便的用apt-get去卸载。如果直接make install的话，还需要保留源码才能再需要卸载的时候卸载掉。

参考:
- [[http://ubuntuhandbook.org/index.php/2014/10/emacs-24-4-released-install-in-ubuntu-14-04/][Emacs 24.4 Released, How to Install it in Ubuntu 14.04]]
- [[http://www.ibm.com/developerworks/cn/linux/l-cn-checkinstall/index.html][Linux 的源码安装工具 CheckInstall]]

* 安装Atom
* 安装Sublime
* 安装SmartGit
* 安装Elementary Tweaks
* 安装搜狗输入法
* Atom支持中文显示
在设置的font-family里填下面的字体，注意要加最后的分号。下面的字体是系统自带的，可以改成你喜好的字体，我用的是从拷贝过来的Consolas和Yahei字体 =Droid Sans Mono, Droid Sans Fallback;= , 网上还有一些免费的中文字体，大家可以选用。

字体：
- [[http://wiki.ubuntu.com.cn/免费中文字体][免费中文字体-Ubuntu中文论坛]]
- [[http://wenq.org/wqy2/index.cgi][文泉驿自由字体]]

* Sublime支持中文输入
进入到我们的usrbin目 =cd ~/.usrbin=, 添加文件subl_im.c，代码如下：
#+begin_src c
#include <gtk/gtkimcontext.h>
void gtk_im_context_set_client_window (GtkIMContext *context,
         GdkWindow    *window)
{
 GtkIMContextClass *klass;
 g_return_if_fail (GTK_IS_IM_CONTEXT (context));
 klass = GTK_IM_CONTEXT_GET_CLASS (context);
 if (klass->set_client_window)
   klass->set_client_window (context, window);
 g_object_set_data(G_OBJECT(context),"window",window);
 if (!GDK_IS_WINDOW (window))
   return;
 int width = gdk_window_get_width(window);
 int height = gdk_window_get_height(window);
 if(width != 0 && height !=0)
   gtk_im_context_focus_in(context);
}
#+end_src

安装gtk2.0的开发包 =sudo apt-get install libgtk2.0-dev= 执行编译命令
#+begin_src sh
gcc -shared -o libsubl-im.so subl_im.c `pkg-config --libs --cflags gtk+-2.0` -fPIC
#+end_src

创建subl文件， =text ~/.usrbin/subl=
#+begin_src sh
#!/bin/bash
LD_PRELOAD=$HOME/.usrbin/libsubl-im.so exec /usr/bin/subl "$@"
#+end_src

修改文件使其可以执行 =sudo chmod +x sublime_text=

用Launcher Manager修改subl的desktop文件，/opt/sublime_text/sublime_text %F 改为subl %F

现在不管是在命令行，还是菜单中进入，都可以输入中文了。

* Scratch支持中文输入
在.usrbin目录下创建scratch-text-editor
#+begin_src sh
#!/bin/bash
GTK_IM_MODULE="xim" exec /usr/bin/scratch-text-editor "$@"
#+end_src

然后再chmod一下，添加可执行权限 =chmod +x scratch-text-editor=

* Emacs中文输入和闪退问题
在usrbin目录下创emacs文件 内容改为
#+begin_src sh
#!/bin/bash
XLIB_SKIP_ARGB_VISUALS=1 LC_CTYPE=zh_CN.UTF-8 exec /usr/bin/emacs
#+end_src

用Launcher Manager修改emacs的Exec为emacs %F。如果在Launchaer Manager找不到emacs的图标，就去/usr/share/applications下找emacs24.desktop这个文件，直接sudo修改这个文件的Exec那一行，Exec=emacs %F。
#+begin_src sh
[Desktop Entry]
Version=1.0
Name=GNU Emacs 24
GenericName=Text Editor
Comment=View and edit files
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
Exec=emacs %F
TryExec=emacs
Icon=/usr/share/icons/hicolor/scalable/apps/emacs24.svg
Type=Application
Terminal=false
Categories=Utility;Development;TextEditor;
StartupWMClass=Emacs24
#+end_src

* ElementaryOS桌面卡死
按快捷键 =Ctrl+Alt+F1= 进入tty1，输入命令 =sudo service lightdm restart=, 这是会进入到登陆界面，但是之前的工作都丢失了。

这两天频繁遇到卡死的问题，网上没有找到解决方法。重新选了显卡驱动也没有解决，后面如果解决了跟进记录在这里。
