#+TITLE: 在Ubuntu系统环境中配置github个人博客octopress
#+DATE: 2015-08-25
#+SETUPFILE: ~/Dev/octopress/setupfile.org
#+OPTIONS: num:1
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES:
#+JEKYLL_PUBLISHED: true

本文记录了自己在Ubunutu环境下折腾octopress的过程.

{{{more}}}

* 我的环境
 | 项            | 版本        |
 |---------------+-------------|
 | Elementary OS | 0.3 (Freya) |
 | Octopress     | 3.0         |

* 安装过程
安装rbenv和ruby-build

#+begin_src sh
sudo apt-get install rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
#+end_src

输入ruby install -l命令,查看可用的安装ruby版本
#+begin_src sh
usage: rbenv install VERSION
       rbenv install /path/to/definition

Available versions:
  1.8.6-p383
  1.8.6-p420
  1.8.7-p249
  1.8.7-p302
  ...
#+end_src

安装编译依赖
#+begin_src sh
apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
#+end_src

选择合适的版本安装，我安装的是最新版的1.9.3-p0
#+begin_src sh
rbenv install 1.9.3-p0
#+end_src

rbenv的工作方式是，在 =$HOME/.rbenv/shims= 目录中，存放你选择的版本的ruby。因此，要把这个目录添加到系统PATH中去，在bashrc中修改:
#+begin_src sh
export PATH=$HOME/.rbenv/shims:$PATH
#+end_src

运行rbenv切换到我们安装的1.9.3的环境中去
#+begin_src sh
rbenv local 1.9.3-p0
rbenv rehash
#+end_src

运行 =source ~/.bashrc= 使改动立即生效。

下载octopress源码，我是在~/Dev下放置我的代码的。
#+begin_src sh
git clone git://github.com/imathis/octopress.git octopress
cd octopress
#+end_src

安装octopress的依赖项，这一步需要梯子，我用的是云梯。
#+begin_src sh
gem install bundler
rbenv rehash
bundle install
#+end_src

在github上创建一个repo，名字须要叫做  =username.github.io= ,其中username就是你的用户名。比如我的用户名是sj20082663, 那repo就是sj20082663.github.io。

使用 =rake setup_github_pages= 连接octopress和github就可以了。

* 使用
到这一步安装其实就已经完成了，基本用法这里不详细的说，只是简单的介绍下：
- rake new_post["setup-octopress-in-ubuntu"]，新建博客。
- rake preview，在 http://localhost:4000 预览。
- rake setup_github_pages, 配置你的github的repo，可以使用https或者ssh，我使用的是ssh.
- rake deploy，部署到github上，部署过程中有任何问题，github会把log发送到你的邮箱的。

* 相关问题
** Q1 Mac下如何安装
Mac下唯一的区别是在rbenv安装ruby的时候有问题，1.9.3须要使用gcc编译，但是mac默认已经不附带gcc了。我在我的Mac上安装的是2.2.0版本，也是一样可以工作的。

** Q2 bundle install总是失败怎么办
bundle install这一步是从服务器上下载ruby的第三方包并安装到当前活动的ruby环境中去。由于这些技术性的网站被屏蔽了，因此，没有办法直接下载。可以使用taobao的RubyGems镜像，[[http://ruby.taobao.org/][淘宝RubyGems镜像]], 执行过程如下：
#+begin_src sh
gem sources --remove https://rubygems.org/
gem sources -a https://ruby.taobao.org/
gem sources -l
    *** CURRENT SOURCES ***
    https://ruby.taobao.org
#+end_src
